---
backend_url: http://localhost:8888/
base_url: http://localhost:8888/
backend_token: TOKEN
secret_key: arbitrary_internal_flask_key
info_email: wolfgang.mauerer@siemens.com
ssl_stapling_resolver: False
google_analytics: False
file_server: localhost
