---
smtp_host: localhost
smtp_user: smtp_user
smtp_sender: cip-kernelci
smtp_sender_desc: CIP KernelCI
smtp_password:
info_email: wolfgang.mauerer@siemens.com
s3_bucket_name:
s3_access_key:
s3_secret_key:
# Note: The master key need not be super secret because the REST service
# is only available internally or for trusted parties with other means
# of access restrictions (ssh authentication)
master_key: SuperSecretMasterKey
zabbix_ip:
ssl_stapling_resolver: FALSE
